steps:
  - name: 'maven'
    entrypoint: 'mvn'
    args: [ 'clean', 'install', '-DskipTests' ]

  # Build the container image
  #https://cloud.google.com/build/docs/cloud-builders
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'build', 'submit', '--tag', 'gcr.io/movies-dashboard-384017/movies-service:latest', '.' ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/movies-dashboard-384017/movies-service:latest' ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'movies-service'
      - '--image'
      - 'gcr.io/movies-dashboard-384017/movies-service:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--quiet'
options:
  logging: CLOUD_LOGGING_ONLY

images: [ gcr.io/movies-dashboard-384017/movies-service:latest ]